### Setup
GET https://example.com

> {%
client.global.set("sessionId", "test-session-" + Date.now());
client.log(client.global.get("sessionId"));
%}

###

GET {{jsonplaceholder}}/todos
sessionId: {{sessionId}}

> {%
client.assert(response.status == 200, "Something went wrong");
client.global.set("todo", JSON.stringify(response.body[0]));
client.log(client.global.get("todo"));
%}

###

POST {{jsonplaceholder}}/todos
sessionId: {{sessionId}}

{{todo}}

> {%
client.assert(response.status == 201, "Something went wrong");
client.global.set("id", response.body.id);
%}
